const QUESTIONS = [

    //飛鳥時代
    { event: "大化の改新", year: 645 },
    { event: "壬申の乱", year: 672 },
    { event: "大宝律令の制定", year: 701 },

    //奈良時代
    { event: "平城京遷都", year: 710 },
    { event: "墾田永年私財法", year: 743 },

    //平安時代
    { event: "平安京遷都", year: 794 },
    { event: "遣唐使廃止", year: 894 },
    { event: "平将門の乱", year: 935 },
    { event: "藤原純友の乱", year: 939 },
    { event: "藤原道長が摂政", year: 1016 },
    { event: "白河上皇院政", year: 1086 },
    { event: "保元の乱", year: 1156 },
    { event: "平治の乱", year: 1159 },
    { event: "平清盛が太政大臣", year: 1167 },

    //鎌倉時代
    { event: "守護地頭設置", year: 1185 },
    { event: "源頼朝が征夷大将軍", year: 1192 },
    { event: "承久の乱", year: 1221 },
    { event: "御成敗式目制定", year: 1232 },
    { event: "文永の役", year: 1274 },
    { event: "弘安の役", year: 1281 },

    // 室町時代
    { event: "建武の新政", year: 1333 },
    { event: "足利尊氏が征夷大将軍", year: 1338 },
    { event: "南北朝合一", year: 1392 },
    { event: "勘合貿易（日明貿易）", year: 1404 },
    { event: "正長の土一揆", year: 1428 },
    { event: "応仁の乱", year: 1467 },
    { event: "鉄砲の伝来", year: 1543 },
    { event: "桶狭間の戦い", year: 1560 },
    { event: "長篠の戦い", year: 1575 },
    { event: "本能寺の変", year: 1582 },
    { event: "太閤検地", year: 1582 },
    { event: "刀狩令", year: 1588 },
    { event: "豊臣秀吉が全国を統一", year: 1590 },
    { event: "文禄の役", year: 1592 },
    { event: "慶長の役", year: 1597 },

    //江戸時代
    { event: "徳川家康が征夷大将軍", year: 1603 },
    { event: "大坂の陣", year: 1615 },
    { event: "最初の武家諸法度", year: 1615 },
    { event: "参勤交代が制度化", year: 1635 },
    { event: "島原・天草の一揆", year: 1637 },
    { event: "ポルトガル船来航禁止（鎖国）", year: 1639 },
    { event: "シャクシャインの戦い", year: 1669 },
    { event: "生類憐みの令", year: 1685 },
    { event: "イギリスで名誉革命", year: 1688 },
    { event: "享保の改革（徳川吉宗）", year: 1716 },
    { event: "田沼意次が老中となる", year: 1772 },
    { event: "アメリカの独立宣言", year: 1776 },
    { event: "寛政の改革（松平定信）", year: 1787 },
    { event: "フランス革命", year: 1789 },
    { event: "ラクスマン来航", year: 1792 },
    { event: "大塩平八郎の乱", year: 1837 },
    { event: "清でアヘン戦争", year: 1840 },
    { event: "天保の改革（水野忠邦）", year: 1841 },
    { event: "清で太平天国の乱", year: 1851 },
    { event: "ペリー来航", year: 1853 },
    { event: "日米和親条約", year: 1854 },
    { event: "日米修好通商条約", year: 1858 },
    { event: "桜田門外の変", year: 1860 },
    { event: "アメリカで南北戦争", year: 1861 },
    { event: "大政奉還", year: 1867 },
    { event: "王政復古の大号令", year: 1867 },
    { event: "戊辰戦争", year: 1868 },
    { event: "版籍奉還", year: 1869 },
    { event: "廃藩置県", year: 1871 },
    { event: "ドイツ統一", year: 1871 },
    { event: "地租改正", year: 1873 },
    { event: "徴兵令", year: 1873 },
    { event: "樺太・千島交換条約", year: 1875 },
    { event: "日朝修好条規", year: 1876 },
    { event: "西南戦争", year: 1877 },
    { event: "国会開設の勅諭", year: 1881 },
    { event: "三国同盟（ドイツ・オーストリア・イタリア）", year: 1882 },
    { event: "大日本帝国憲法の発布", year: 1889 },
    { event: "第一回帝国議会の開会", year: 1890 },
    { event: "日清戦争", year: 1894 },
    { event: "治外法権の撤廃", year: 1894 },
    { event: "甲午農民戦争", year: 1894 },
    { event: "下関条約", year: 1895 },
    { event: "義和団事件", year: 1899 },
    { event: "足尾銅山鉱毒事件", year: 1901 },
    { event: "日英同盟", year: 1902 },
    { event: "日露戦争", year: 1904 },
    { event: "ポーツマス条約", year: 1905 },
    { event: "三国協商（イギリス・フランス・ロシア）", year: 1907 },
    { event: "韓国併合", year: 1910 },
    { event: "関税自主権の回復", year: 1911 },
    { event: "辛亥革命", year: 	1911 },
    { event: "二十一か条の要求", year: 1915 },
    { event: "第一次世界大戦", year: 	1914 },
    { event: "ロシア革命", year: 1917 },
    { event: "米騒動", year: 1918 },
    { event: "原敬の政党内閣が成立", year: 1918 },
    { event: "三・一独立運動", year: 1919 },
    { event: "五・四運動", year: 1919 },
    { event: "国際連盟に加入", year: 1920 },
    { event: "ソビエト連邦が成立", year: 1922 },
    { event: "治安維持法の成立", year: 	1925 },
    { event: "普通選挙法", year: 	1925 },
    { event: "満州事変", year: 	1931 },
    { event: "五・一五事件", year: 1932 },
    { event: "国際連盟を脱退", year: 1933 },
    { event: "ドイツにヒトラー政権成立", year: 1933 },
    { event: "二・二六事件", year: 1936 },
    { event: "日中戦争がはじまる", year: 1937 },
    { event: "日独伊三国同盟", year: 1940 },
    { event: "太平洋戦争がはじまる", year: 1941 },
    { event: "ポツダム宣言の受諾", year: 1945 },
    { event: "国際連合の発足", year: 1945 },
    { event: "日本国憲法の公布", year: 	1946 },
    { event: "教育基本法の公布", year: 	1947 },
    { event: "北大西洋条約機構（NATO）", year: 1949},
    { event: "朝鮮戦争はじまる", year: 1950 },
    { event: "サンフランシスコ平和条約", year: 1951 },
    { event: "奄美諸島の日本復帰", year: 1953 },
    { event: "アジア・アフリカ会議", year: 1955 },
    { event: "国際連合に加盟", year: 1956 },
    { event: "ベトナム戦争はじまる", year: 1960 },
    { event: "日韓基本条約", year: 1965 },
    { event: "東西ドイツの統一", year: 1990 },
    { event: "湾岸戦争", year: 1991 },
    { event: "東日本大震災", year: 2011 }
];